### ISSUE TITLE
[feature] Feedback for Clicking the Connect Button

### ISSUE THREAD

**Issue by QingZ11** [wey-gu/NebulaGraph-Gephi#11]
After clicking the "connect" button, the user should be provided with feedback indicating whether the connection was successful or not. Additionally, if the connection is successful, the login interface on the right side should disappear.

![image](https://github.com/wey-gu/NebulaGraph-Gephi/assets/38887077/5094a68e-5cda-4ef6-8033-7171a29614b1)

**Comment by wey-gu** [comment]
Makes a lot of sense! Will considering adding this!
